### ISSUE TITLE
Patch Update 0.4.28 is a breaking change

### ISSUE THREAD

**Issue by jafreck** [Azure/msrestazure-for-python#90]
Yesterday, with the 0.4.28 update, a breaking change was introduced since keyring was removed as a dependency but is still required for some functionality. Upstream libraries that have correct semantic versioning have been broken as a result. Can this patch be reverted and replaced with a increase in the major version?

Or, since [SecretStroage updated to fix the breaking issue ](https://pypi.org/project/SecretStorage/#history) can the keyring dependency be re-added?

**Comment by jafreck** [comment]
@lmazuel Is there anything that can be done here?

**Comment by lmazuel** [comment]
The problem is not secretstorage, the problem is "keyring":
https://github.com/jaraco/keyring/issues/321

Since we need Python 2.7 support, we're now stuck forever at "keyring" 12.0.2.

Note that "keyring" was barely already optional, so I would be curious to understand your scenario?

**Comment by jafreck** [comment]
Keyring is still required for ServicePrincipalCredential auth for many of the azure python sdk management clients. [We use this to authenticate Batch and Storage management clients using aad credentials](https://github.com/Azure/aztk/blob/3cc43c3277dd8a51ba96a606978c745888952d6d/aztk/node_scripts/core/config.py#L47). 

This means that msrestazure is being shipped with key features (the ability to authenticate with ServicePrincipalCredentials) broken out of the box. 

Also, this change is breaking but it's being shipped as a patch update version.

**Comment by lmazuel** [comment]
"keyring" is not required to use `ServicePrincipalCredentials` at all. "keyring" is optional since [msrestazure 0.4.13](https://github.com/Azure/msrestazure-for-python#2017-08-24-version-0413).

If you have a stacktrace of failure of a regular ServicePrincipalCredentials call since msrestazure 0.4.28, please share.

Note that I don't say at this point I won't fix (or I will fix :)), I want to get full context to do the right thing.

**Comment by jafreck** [comment]
I think I may not be properly explaining the issue.

So, msrestazure version 0.4.0 to 0.4.12 requires keyring. 0.4.13 to 0.4.27 has keyring as optional, and 0.4.28 removes keyring as a dependency. This is a breaking change within the same minor version (which should maintain backwards compatibility). This means that any upstream repository that has specified `msrestazure~=0.4.X` in accordance with [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release) has been broken if it relies on keyring being available. 

The azure-batch package is an example of this. Version 4.0.0 specifies msrestazrue in setup.py with: [install_requires "msrestazure~=0.4.11"](https://github.com/Azure/azure-sdk-for-python/blob/fbc86e377617b7c20b7876f5cc8198c381d362ce/azure-batch/setup.py#L81). This means that the newest patch update 0.4.28 is pulled in as a dependency. [Since the batch client relies on keyring being installed](https://github.com/Azure/azure-sdk-for-python/blob/azure_3.0.0/azure-batch/azure/batch/batch_auth.py), this causes a `ModuleNotFoundError: no module  named 'keyring'` when you try to auth.

To repro:
1. `pip install azure-batch==4.0.0`
2. `python -c 'import azure.batch.batch_auth'`
3. stacktrace:
```
>>> import azure.batch.batch_auth as batch_auth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\azure\batch\batch_auth.py", line 9, in <module>
    import keyring
ModuleNotFoundError: No module named 'keyring'
```

**Comment by lmazuel** [comment]
So, let's separate the issues:
- Batch is wrong, they import in their own files `keyring`, this means they should depends explicitly on `keyring`. You can't rely on an indirect dependency for your code. I fixed that in azure-batch 4.1.1 ([see ChangeLog](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-batch/HISTORY.rst#412-2018-04-23)). I was kind in the ChangeLog, I could have said "Remove a pointless unused import". Everybody that uses explicitly `keyring` should depend explicitly on `keyring` and don't expect `msrestazure` to bring it. I can change my backend tomorrow and change entirely my dependency system, and no-one should care that not the same packages are installed.
- Since `keyring` is already optional, the only scenario that it breaks is if you use the token cache mechanism. If you were using it, it breaks installing 0.4.28, which is not cool. The problem is not `keyring`, it's that the "token cache mechanism needs now an extra step to be enabled". And that indeed should not be within the same minor version. On the other hand, this was the only fast way I had to unlock the entire CLI/SDK packaging system to work again (every installation of anything on 2.7 and 3.4 just wasn't possible at all).

Now that `keyring` fixed, I can get it back with a `keyring>=12.0.2` in a 0.4.29 version.

**Comment by jafreck** [comment]
Ah, I see. Thanks for the explanation, that makes sense. It is unfortunate that all old versions of Batch are broken, but I see now that this isn't msrestazure's fault.

Releasing a 0.4.29 with keyring again would fix the issues I am having, but that doesn't solve the underlying issue for pre-4.1.1 Batch releases. Thanks again!
